version: '3.1'

services:
  zookeeper-server:
    image: bitnami/zookeeper:3.8.0
    restart: always
    ports:
      - '2181:2181'
    networks:
      - kafka-bridge
    volumes:
      - kafka-volume
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=kafka
      - ZOO_SERVER_PASSWORDS=kafka_password

  kafka:
    image: bitnami/kafka:3.3.1
    restart: always
    networks:
      - kafka-bridge
    volumes:
      - kafka-volume
    ports:
      - '9092:9092'

    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9093,OUTSIDE://localhost:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_ZOOKEEPER_PASSWORD=kafka_password
      - KAFKA_ZOOKEEPER_USER=kafka

  kafka-ui:
    image: provectuslabs/kafka-ui:a2e87cc8d5ba21e2b01f2f240926298f382db63c
    container_name: kafka-ui
    ports:
      - "9090:8080"
    restart: always
    networks:
      - kafka-bridge
    volumes:
      - kafka-volume
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9093
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper-server:2181


networks:
  kafka-bridge:
    driver: bridge
volumes:
  kafka-volume:


